### ISSUE TITLE
table containing caption - ClassCastException

### ISSUE THREAD

**Issue by plutext** [plutext/flyingsaucer#1]
<table>
      <caption>
        Table with caption
      </caption>
      <tbody>
        <tr>
          <td>r1c1</td>
          <td>r1c2</td>
        </tr>
        <tr>
          <td>r2c1</td>
          <td>r2c2</td>
        </tr>
        </tbody>
</table>

causes the following error:

Exception in thread "main" java.lang.ClassCastException: org.docx4j.org.xhtmlrenderer.render.BlockBox cannot be cast to org.docx4j.org.xhtmlrenderer.newtable.TableSectionBox
    at org.docx4j.org.xhtmlrenderer.newtable.TableBox.recalcSections(TableBox.java:208)
    at org.docx4j.org.xhtmlrenderer.newtable.TableBox.calcMinMaxWidth(TableBox.java:159)
    at org.docx4j.org.xhtmlrenderer.newtable.TableBox.layout(TableBox.java:226)
    at org.docx4j.org.xhtmlrenderer.docx.DocxRenderer.layout(DocxRenderer.java:187)

The error goes away if:
1. you wrap the whole thing in a div; OR
2. you remove the caption

**Comment by plutext** [comment]
&lt;table>
      &lt;caption>
        Table with caption
      &lt;/caption>
      &lt;tbody>
        &lt;tr>
          &lt;td>r1c1&lt;/td>
          &lt;td>r1c2&lt;/td>
        &lt;/tr>
        &lt;tr>
          &lt;td>r2c1&lt;/td>
          &lt;td>r2c2&lt;/td>
        &lt;/tr>
        &lt;/tbody>
&lt;/table>
